spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/alurafood-pedidos?createDatabaseIfNotExist=true}
    username: ${DB_USER_NAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true