spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/alurafood-pedidos?createDatabaseIfNotExist=true}
    username: ${DB_USER_NAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  application:
    name: pedido-ms

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 4
          initial-interval: 5000
          multiplier: 2
          max-interval: 300000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

  instance:
    instance-id: ${spring:application:name}:${random:int}

server:
  port: 0