

spring:
  profiles:
    active: ${APP_PROFILE:dev}

  application:
    name: pedido-ms

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

  instance:
    instance-id: ${spring:application:name}:${random:int}

server:
  port: 0